markdown: rdiscount 
permalink: /:categories/:title 
title: 诗云
url: http://sync.sh
subscribe: http://sync.sh/feed.xml
exclude: [ README.md, newpost.rb ]
domain: sync.sh
author: Fengz
email: enjoyforfun+blog@gmail.com
auto: true
twitterID: ycf
duoshuoShortname: sync